name: Databricks Bundle CI/CD

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  databricks:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Python (Databricks CLI requires Python)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3. Install Databricks CLI
      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
          databricks --version

      # 5. Run validation on PRs
      - name: Validate bundle (PRs)
        if: github.event_name == 'pull_request'
        run: |
          export DATABRICKS_HOST="${{ secrets.DATABRICKS_HOST }}"
          export DATABRICKS_CLIENT_ID="${{ secrets.DATABRICKS_CLIENT_ID }}"
          export DATABRICKS_CLIENT_SECRET="${{ secrets.DATABRICKS_CLIENT_SECRET }}"
          export DATABRICKS_ACCOUNT_ID="${{ secrets.DATABRICKS_ACCOUNT_ID }}"
          cd technical-support-overview-bundle
          databricks bundle validate

      # 6. Deploy on merges to main
      - name: Deploy bundle (main)
        if: github.event_name == 'push'
        run: |
          export DATABRICKS_HOST="${{ secrets.DATABRICKS_HOST }}"
          export DATABRICKS_CLIENT_ID="${{ secrets.DATABRICKS_CLIENT_ID }}"
          export DATABRICKS_CLIENT_SECRET="${{ secrets.DATABRICKS_CLIENT_SECRET }}"
          export DATABRICKS_ACCOUNT_ID="${{ secrets.DATABRICKS_ACCOUNT_ID }}"
          cd technical-support-overview-bundle
          databricks bundle deploy --target prod --auto-approve
